// Products
export const GET_ALL_PRODUCTS = 'GET ALL PRODUCTS';
export const GET_PRODUCTS_PER_DAY = 'GET PRODUCTS PER DAY';
export const TOOGLE_MODAL_PRODUCTS = 'TOOGLE MODAL PRODUCTS';
export const TOOGLE_FETCH_PROD_BY_DAY_LOADER = 'TOOGLE FETCH LOADER';
export const TOOGLE_FETCH_ALL_PROD_LOADER = 'TOOGLE FETCH ALL PROPD LOADER';
export const DELETE_PRODUCT_FROM_PRODUCTLIST = 'DELETE_PRODUCT_FROM_PRODUCTLIST';
