// Products
export const DELETE_PRODUCT_FROM_PRODUCTLIST = 'DELETE_PRODUCT_FROM_PRODUCTLIST';
export const actionTypes = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  ADD_PRODUCT_BY_DATE: 'ADD_PRODUCT_BY_DATE',
  USER_DATA: 'USER_DATA'
};
